DROP TABLE IF EXISTS `page_tag`;
--;;
DROP TABLE IF EXISTS `page_block_tag`;
--;;
DROP TABLE IF EXISTS `page_block_html`;
--;;
DROP TABLE IF EXISTS `page_block_heading`;
--;;
DROP TABLE IF EXISTS `page_block_file`;
--;;
DROP TABLE IF EXISTS `page_block_badge`;
--;;
DROP TABLE IF EXISTS `page`;